INSERT INTO PLAYERS(name) VALUES ('Liam');
INSERT INTO PLAYERS(name) VALUES ('Noah');
INSERT INTO PLAYERS(name) VALUES ('Oliver');
INSERT INTO PLAYERS(name) VALUES ('Char');
INSERT INTO PLAYERS(name) VALUES ('James');
INSERT INTO PLAYERS(name) VALUES ('Henry');
INSERT INTO PLAYERS(name) VALUES ('Mateo');
INSERT INTO PLAYERS(name) VALUES ('Elijah');
INSERT INTO PLAYERS(name) VALUES ('Lucas');
INSERT INTO PLAYERS(name) VALUES ('William');
INSERT INTO PLAYERS(name) VALUES ('Olivia');
INSERT INTO PLAYERS(name) VALUES ('Emma');
INSERT INTO PLAYERS(name) VALUES ('Amelia');
INSERT INTO PLAYERS(name) VALUES ('Charlotte');
INSERT INTO PLAYERS(name) VALUES ('Mia');
INSERT INTO PLAYERS(name) VALUES ('Charlet');
INSERT INTO PLAYERS(name) VALUES ('Isabella');
INSERT INTO PLAYERS(name) VALUES ('Evelyn');
INSERT INTO PLAYERS(name) VALUES ('Ava');
INSERT INTO PLAYERS(name) VALUES ('Sofia');

INSERT INTO MATCHES (player1, player2, winner) VALUES (1, 2, 1);
INSERT INTO MATCHES (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO MATCHES (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO MATCHES (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO MATCHES (player1, player2, winner) VALUES (9, 10, 10);
INSERT INTO MATCHES (player1, player2, winner) VALUES (4, 14, 4);
INSERT INTO MATCHES (player1, player2, winner) VALUES (14, 16, 16);
INSERT INTO MATCHES (player1, player2, winner) VALUES (4, 16, 16);
INSERT INTO MATCHES (player1, player2, winner) VALUES (11, 12, 12);
INSERT INTO MATCHES (player1, player2, winner) VALUES (13, 14, 14);
INSERT INTO MATCHES (player1, player2, winner) VALUES (15, 16, 15);
INSERT INTO MATCHES (player1, player2, winner) VALUES (17, 18, 17);
INSERT INTO MATCHES (player1, player2, winner) VALUES (19, 20, 20);
INSERT INTO MATCHES (player1, player2, winner) VALUES (1, 2, 1);