INSERT INTO PLAYERS(name) VALUES ('Евгений Кафельников');
INSERT INTO PLAYERS(name) VALUES ('Roger Federer');
INSERT INTO PLAYERS(name) VALUES ('Дж. К. Роулинг');
INSERT INTO PLAYERS(name) VALUES ('Д''Артаньян');
INSERT INTO PLAYERS(name) VALUES ('Jean-Luc');
INSERT INTO PLAYERS(name) VALUES ('Anne-Marie O''Neil');
INSERT INTO PLAYERS(name) VALUES ('Mateo');
INSERT INTO PLAYERS(name) VALUES ('Elijah');
INSERT INTO PLAYERS(name) VALUES ('Lucas');
INSERT INTO PLAYERS(name) VALUES ('William');
INSERT INTO PLAYERS(name) VALUES ('Olivia');
INSERT INTO PLAYERS(name) VALUES ('Emma');
INSERT INTO PLAYERS(name) VALUES ('Amelia');
INSERT INTO PLAYERS(name) VALUES ('Charlotte');
INSERT INTO PLAYERS(name) VALUES ('Mia');
INSERT INTO PLAYERS(name) VALUES ('Charlet');
INSERT INTO PLAYERS(name) VALUES ('Isabella');
INSERT INTO PLAYERS(name) VALUES ('Evelyn');
INSERT INTO PLAYERS(name) VALUES ('Ava');
INSERT INTO PLAYERS(name) VALUES ('Sofia');
INSERT INTO PLAYERS(name) VALUES ('Charlatte');
INSERT INTO PLAYERS(name) VALUES ('LatteChar');

INSERT INTO MATCHES (player1, player2, winner) VALUES (1, 2, 1);
INSERT INTO MATCHES (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO MATCHES (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO MATCHES (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO MATCHES (player1, player2, winner) VALUES (9, 10, 10);
INSERT INTO MATCHES (player1, player2, winner) VALUES (4, 14, 4);
INSERT INTO MATCHES (player1, player2, winner) VALUES (14, 16, 16);
INSERT INTO MATCHES (player1, player2, winner) VALUES (4, 16, 16);
INSERT INTO MATCHES (player1, player2, winner) VALUES (11, 12, 12);
INSERT INTO MATCHES (player1, player2, winner) VALUES (13, 14, 14);
INSERT INTO MATCHES (player1, player2, winner) VALUES (15, 16, 15);
INSERT INTO MATCHES (player1, player2, winner) VALUES (17, 18, 17);
INSERT INTO MATCHES (player1, player2, winner) VALUES (19, 20, 20);
INSERT INTO MATCHES (player1, player2, winner) VALUES (21, 22, 21);
INSERT INTO MATCHES (player1, player2, winner) VALUES (21, 22, 22);